### PR TITLE
Migration and initial packaging

### PR DESCRIPTION
**Pull request by kdeldycke**
Work started by @cav71.

### CODE REVIEW

**Comment by justinmayer** [comment]
Many thanks to @cav71 and @kdeldycke for the work on migrating this plugin. There are some areas that I think could be improved, and there are enough that it's easier for me to push an alternate branch than to comment on the commits in the existing `migrate` branch. I'll post another comment here when it's ready to review.

**Comment by justinmayer** [comment]
I pushed a new branch called [`convert`](https://github.com/pelican-plugins/show-source/tree/convert) that conveys my ideas regarding what the "Show Source" plugin migration should look like.

Please take a look at the contents of that branch and compare to the `migrate` branch. After sufficient time for discussion and consensus, we can either change the contents of `migrate` to reflect the contents of `convert`, or we can merge the `convert` branch. I'm totally okay with either of those options. 

I'm also cc'ing @chrisramsay in case he has any input, since he is the original author of this plugin. (Thanks, Chris!) 😸

**Comment by kdeldycke** [comment]
Oh thanks @justinmayer ! I was planning to update @cav71 initial proposal to have it more in line with the way we migrate plugin. But you were faster than me! 😃

@justinmayer: your proposal looks indeed cleaner. I propose to have it merged right away as `main` and release it. That way we can clear of the work on that plugin and move on.

**Comment by cav71** [comment]
looks good to me. thanks!

**Comment by justinmayer** [comment]
Glad to hear. In that case, I will close this in favor of #5.

**Pull request closed without merging**
